# yaml-language-server: $schema=https://raw.githubusercontent.com/suzuki-shunsuke/pinact/main/json-schema/pinact.json
version: 3

ignore_actions:
  - name: "JackPlowman/coding-metrics"
    ref: "main"
